<?php
return [
    'router' => [
        'routes' => [
            'medical-record.rest.diagnosa' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/diagnosa[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.operasi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/operasi[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Operasi\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.icd10' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/icd10[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\ICD10\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.icd9-cm' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/icd9cm[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.operasi-di-tindakan' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/operasiditindakan[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.icd10-kematian' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/icd10kematian[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.anamnesis' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis[/:anamnesis_id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.pemeriksaan-fisik' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/pemeriksaan/fisik[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.riwayat-perjalanan-penyakit' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/riwayat/perjalananpenyakit[/:riwayat_perjalanan_penyakit_id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.riwayat-alergi' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/riwayat/alergi[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.tanda-vital' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/pemeriksaan/umum/tandavital[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\TandaVital\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.peminjaman-berkas' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/peminjamanberkas[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.peminjaman-berkas1' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/peminjamanberkas1[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.cppt' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/cppt[/:cppt_id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\CPPT\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.riwayat-pemberian-obat' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/riwayat/pemberianobat[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\RiwayatPemberianObat\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.keluhan-utama' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/keluhan/utama[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\KeluhanUtama\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.status-fungsional' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/statusfungsional[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\StatusFungsional\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.kondisi-sosial' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/kondisisosial[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\KondisiSosial\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.edukasi-pasien-keluarga' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/edukasipasienkeluarga[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\EdukasiPasienKeluarga\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.edukasi-emergency' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/edukasipasienkeluarga/emergency[/:edukasi_id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\EdukasiEmergency\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.permasalah-gizi-pasien' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/anamnesis/permasalahangizi[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PermasalahGiziPasien\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.pemeriksaan-umum' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/pemeriksaan/umum/nutrisi[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PemeriksaanUmum\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.fungsional' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/pemeriksaan/umum/fungsional[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Fungsional\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.penilaian-fisik' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/penilaian/fisik[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PenilaianFisik\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.penilaian-nyeri' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/penilaian/nyeri[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\PenilaianNyeri\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.status-pediatric' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/penilaian/statuspediatric[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\StatusPediatric\\Controller',
                    ],
                ],
            ],
            'medical-record.rest.diagnosis' => [
                'type' => 'Segment',
                'options' => [
                    'route' => '/medicalrecord/penilaian/diagnosis[/:id]',
                    'defaults' => [
                        'controller' => 'MedicalRecord\\V1\\Rest\\Diagnosis\\Controller',
                    ],
                ],
            ],
        ],
    ],
    'api-tools-versioning' => [
        'uri' => [
            0 => 'medical-record.rest.diagnosa',
            1 => 'medical-record.rest.operasi',
            2 => 'medical-record.rest.icd10',
            3 => 'medical-record.rest.icd9-cm',
            4 => 'medical-record.rest.operasi-di-tindakan',
            5 => 'medical-record.rest.icd10-kematian',
            6 => 'medical-record.rest.anamnesis',
            7 => 'medical-record.rest.pemeriksaan-fisik',
            29 => 'medical-record.rest.riwayat-perjalanan-penyakit',
            30 => 'medical-record.rest.riwayat-alergi',
            31 => 'medical-record.rest.tanda-vital',
            32 => 'medical-record.rest.peminjaman-berkas',
            33 => 'medical-record.rest.peminjaman-berkas1',
            34 => 'medical-record.rest.cppt',
            35 => 'medical-record.rest.riwayat-pemberian-obat',
            36 => 'medical-record.rest.keluhan-utama',
            37 => 'medical-record.rest.status-fungsional',
            38 => 'medical-record.rest.kondisi-sosial',
            39 => 'medical-record.rest.edukasi-pasien-keluarga',
            40 => 'medical-record.rest.edukasi-emergency',
            41 => 'medical-record.rest.permasalah-gizi-pasien',
            42 => 'medical-record.rest.pemeriksaan-umum',
            43 => 'medical-record.rest.fungsional',
            44 => 'medical-record.rest.penilaian-fisik',
            45 => 'medical-record.rest.penilaian-nyeri',
            46 => 'medical-record.rest.status-pediatric',
            47 => 'medical-record.rest.diagnosis',
        ],
    ],
    'service_manager' => [
        'factories' => [
            \MedicalRecord\V1\Rest\Diagnosa\DiagnosaResource::class => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaResourceFactory::class,
            \MedicalRecord\V1\Rest\Operasi\OperasiResource::class => \MedicalRecord\V1\Rest\Operasi\OperasiResourceFactory::class,
            \MedicalRecord\V1\Rest\ICD10\ICD10Resource::class => \MedicalRecord\V1\Rest\ICD10\ICD10ResourceFactory::class,
            \MedicalRecord\V1\Rest\ICD9CM\ICD9CMResource::class => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMResourceFactory::class,
            \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanResource::class => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanResourceFactory::class,
            \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianResource::class => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianResourceFactory::class,
            \MedicalRecord\V1\Rest\Anamnesis\AnamnesisResource::class => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisResourceFactory::class,
            \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikResource::class => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikResourceFactory::class,
            \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitResource::class => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitResourceFactory::class,
            \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiResource::class => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiResourceFactory::class,
            \MedicalRecord\V1\Rest\TandaVital\TandaVitalResource::class => \MedicalRecord\V1\Rest\TandaVital\TandaVitalResourceFactory::class,
            \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasResource::class => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasResourceFactory::class,
            \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Resource::class => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1ResourceFactory::class,
            \MedicalRecord\V1\Rest\CPPT\CPPTResource::class => \MedicalRecord\V1\Rest\CPPT\CPPTResourceFactory::class,
            \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatResource::class => \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatResourceFactory::class,
            \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaResource::class => \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaResourceFactory::class,
            \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalResource::class => \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalResourceFactory::class,
            \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialResource::class => \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialResourceFactory::class,
            \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaResource::class => \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaResourceFactory::class,
            \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyResource::class => \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyResourceFactory::class,
            \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienResource::class => \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienResourceFactory::class,
            \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumResource::class => \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumResourceFactory::class,
            \MedicalRecord\V1\Rest\Fungsional\FungsionalResource::class => \MedicalRecord\V1\Rest\Fungsional\FungsionalResourceFactory::class,
            \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikResource::class => \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikResourceFactory::class,
            \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriResource::class => \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriResourceFactory::class,
            \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricResource::class => \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricResourceFactory::class,
            \MedicalRecord\V1\Rest\Diagnosis\DiagnosisResource::class => \MedicalRecord\V1\Rest\Diagnosis\DiagnosisResourceFactory::class,
        ],
    ],
    'api-tools-rest' => [
        'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaResource::class,
            'route_name' => 'medical-record.rest.diagnosa',
            'route_identifier_name' => 'id',
            'collection_name' => 'diagnosa',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'UTAMA',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Diagnosa\DiagnosaCollection::class,
            'service_name' => 'Diagnosa',
        ],
        'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Operasi\OperasiResource::class,
            'route_name' => 'medical-record.rest.operasi',
            'route_identifier_name' => 'id',
            'collection_name' => 'operasi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'DOKTER',
                2 => 'STATUS',
                3 => 'KUNJUNGAN',
                4 => 'TANGGAL',
                5 => 'NORM',
                6 => 'NAMA_OPERASI',
                7 => 'start',
                8 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Operasi\OperasiEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Operasi\OperasiCollection::class,
            'service_name' => 'Operasi',
        ],
        'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\ICD10\ICD10Resource::class,
            'route_name' => 'medical-record.rest.icd10',
            'route_identifier_name' => 'id',
            'collection_name' => 'icd10',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'UTAMA',
                3 => 'STATUS',
                4 => 'INA_GROUPER',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\ICD10\ICD10Entity::class,
            'collection_class' => \MedicalRecord\V1\Rest\ICD10\ICD10Collection::class,
            'service_name' => 'ICD10',
        ],
        'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMResource::class,
            'route_name' => 'medical-record.rest.icd9-cm',
            'route_identifier_name' => 'id',
            'collection_name' => 'icd9_cm',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'TINDAKAN',
                3 => 'STATUS',
                4 => 'INA_GROUPER',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\ICD9CM\ICD9CMCollection::class,
            'service_name' => 'ICD9CM',
        ],
        'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanResource::class,
            'route_name' => 'medical-record.rest.operasi-di-tindakan',
            'route_identifier_name' => 'id',
            'collection_name' => 'operasi_di_tindakan',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'ID',
                1 => 'TINDAKAN_MEDIS',
                2 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanCollection::class,
            'service_name' => 'OperasiDiTindakan',
        ],
        'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianResource::class,
            'route_name' => 'medical-record.rest.icd10-kematian',
            'route_identifier_name' => 'id',
            'collection_name' => 'icd10_kematian',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NOPEN',
                1 => 'KODE',
                2 => 'UTAMA',
                3 => 'STATUS',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianCollection::class,
            'service_name' => 'ICD10Kematian',
        ],
        'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisResource::class,
            'route_name' => 'medical-record.rest.anamnesis',
            'route_identifier_name' => 'anamnesis_id',
            'collection_name' => 'anamnesis',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'PENDAFTARAN',
                2 => 'STATUS',
                3 => 'NORM',
                4 => 'HISTORY',
                5 => 'NOT',
                6 => 'sort',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Anamnesis\AnamnesisCollection::class,
            'service_name' => 'Anamnesis',
        ],
        'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikResource::class,
            'route_name' => 'medical-record.rest.pemeriksaan-fisik',
            'route_identifier_name' => 'id',
            'collection_name' => 'pemeriksaan_fisik',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'PENDAFTARAN',
                2 => 'STATUS',
                3 => 'NORM',
                4 => 'HISTORY',
                5 => 'NOT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikCollection::class,
            'service_name' => 'PemeriksaanFisik',
        ],
        'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitResource::class,
            'route_name' => 'medical-record.rest.riwayat-perjalanan-penyakit',
            'route_identifier_name' => 'riwayat_perjalanan_penyakit_id',
            'collection_name' => 'riwayat_perjalanan_penyakit',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NORM',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'start',
                6 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitCollection::class,
            'service_name' => 'RiwayatPerjalananPenyakit',
        ],
        'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiResource::class,
            'route_name' => 'medical-record.rest.riwayat-alergi',
            'route_identifier_name' => 'id',
            'collection_name' => 'riwayat_alergi',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NORM',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'limit',
                6 => 'sort',
                7 => 'start',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiCollection::class,
            'service_name' => 'RiwayatAlergi',
        ],
        'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\TandaVital\TandaVitalResource::class,
            'route_name' => 'medical-record.rest.tanda-vital',
            'route_identifier_name' => 'id',
            'collection_name' => 'tanda_vital',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NOT',
                3 => 'sort',
                4 => 'HISTORY',
                5 => 'OLEH',
                6 => 'NORM',
                7 => 'limit',
                8 => 'start',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\TandaVital\TandaVitalEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\TandaVital\TandaVitalCollection::class,
            'service_name' => 'TandaVital',
        ],
        'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasResource::class,
            'route_name' => 'medical-record.rest.peminjaman-berkas',
            'route_identifier_name' => 'id',
            'collection_name' => 'peminjaman_berkas',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NORM',
                1 => 'NO_IDENTITAS',
                2 => 'STATUS',
                3 => 'TLP',
                4 => 'JENIS_KELAMIN',
                5 => 'QUERY',
                6 => 'EMAIL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasCollection::class,
            'service_name' => 'PeminjamanBerkas',
        ],
        'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Resource::class,
            'route_name' => 'medical-record.rest.peminjaman-berkas1',
            'route_identifier_name' => 'id',
            'collection_name' => 'peminjaman_berkas1',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'NORM',
                1 => 'STATUS',
                2 => 'TLP',
                3 => 'EMAIL',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Entity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Collection::class,
            'service_name' => 'PeminjamanBerkas1',
        ],
        'MedicalRecord\\V1\\Rest\\CPPT\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\CPPT\CPPTResource::class,
            'route_name' => 'medical-record.rest.cppt',
            'route_identifier_name' => 'cppt_id',
            'collection_name' => 'cppt',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'sort',
                3 => 'NOT',
                4 => 'NORM',
                5 => 'HISTORY',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\CPPT\CPPTEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\CPPT\CPPTCollection::class,
            'service_name' => 'CPPT',
        ],
        'MedicalRecord\\V1\\Rest\\RiwayatPemberianObat\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatResource::class,
            'route_name' => 'medical-record.rest.riwayat-pemberian-obat',
            'route_identifier_name' => 'id',
            'collection_name' => 'riwayat_pemberian_obat',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'STATUS',
                1 => 'OLEH',
                2 => 'HISTORY',
                3 => 'NOT',
                4 => 'NORM',
                5 => 'sort',
                6 => 'KUNJUNGAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatCollection::class,
            'service_name' => 'RiwayatPemberianObat',
        ],
        'MedicalRecord\\V1\\Rest\\KeluhanUtama\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaResource::class,
            'route_name' => 'medical-record.rest.keluhan-utama',
            'route_identifier_name' => 'id',
            'collection_name' => 'keluhan_utama',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NORM',
                3 => 'HISTORY',
                4 => 'NOT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaCollection::class,
            'service_name' => 'KeluhanUtama',
        ],
        'MedicalRecord\\V1\\Rest\\StatusFungsional\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalResource::class,
            'route_name' => 'medical-record.rest.status-fungsional',
            'route_identifier_name' => 'id',
            'collection_name' => 'status_fungsional',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'NORM',
                4 => 'HISTORY',
                5 => 'NOT',
                6 => 'start',
                7 => 'limit',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalCollection::class,
            'service_name' => 'StatusFungsional',
        ],
        'MedicalRecord\\V1\\Rest\\KondisiSosial\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialResource::class,
            'route_name' => 'medical-record.rest.kondisi-sosial',
            'route_identifier_name' => 'id',
            'collection_name' => 'kondisi_sosial',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'HISTORY',
                4 => 'sort',
                5 => 'NORM',
                6 => 'NOT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialCollection::class,
            'service_name' => 'KondisiSosial',
        ],
        'MedicalRecord\\V1\\Rest\\EdukasiPasienKeluarga\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaResource::class,
            'route_name' => 'medical-record.rest.edukasi-pasien-keluarga',
            'route_identifier_name' => 'id',
            'collection_name' => 'edukasi_pasien_keluarga',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'PENDAFTARAN',
                2 => 'STATUS',
                3 => 'NORM',
                4 => 'HISTORY',
                5 => 'NOT',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaCollection::class,
            'service_name' => 'EdukasiPasienKeluarga',
        ],
        'MedicalRecord\\V1\\Rest\\EdukasiEmergency\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyResource::class,
            'route_name' => 'medical-record.rest.edukasi-emergency',
            'route_identifier_name' => 'edukasi_emergency_id',
            'collection_name' => 'edukasi_emergency',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'NOT',
                3 => 'HISTORY',
                4 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyCollection::class,
            'service_name' => 'EdukasiEmergency',
        ],
        'MedicalRecord\\V1\\Rest\\PermasalahGiziPasien\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienResource::class,
            'route_name' => 'medical-record.rest.permasalah-gizi-pasien',
            'route_identifier_name' => 'id',
            'collection_name' => 'permasalah_gizi_pasien',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'sort',
                6 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienCollection::class,
            'service_name' => 'PermasalahGiziPasien',
        ],
        'MedicalRecord\\V1\\Rest\\PemeriksaanUmum\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumResource::class,
            'route_name' => 'medical-record.rest.pemeriksaan-umum',
            'route_identifier_name' => 'id',
            'collection_name' => 'pemeriksaan_umum',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'OLEH',
                2 => 'STATUS',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'sort',
                6 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumCollection::class,
            'service_name' => 'PemeriksaanUmum',
        ],
        'MedicalRecord\\V1\\Rest\\Fungsional\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Fungsional\FungsionalResource::class,
            'route_name' => 'medical-record.rest.fungsional',
            'route_identifier_name' => 'id',
            'collection_name' => 'fungsional',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'sort',
                6 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Fungsional\FungsionalEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Fungsional\FungsionalCollection::class,
            'service_name' => 'Fungsional',
        ],
        'MedicalRecord\\V1\\Rest\\PenilaianFisik\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikResource::class,
            'route_name' => 'medical-record.rest.penilaian-fisik',
            'route_identifier_name' => 'id',
            'collection_name' => 'penilaian_fisik',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'HISTORY',
                3 => 'NOT',
                4 => 'sort',
                5 => 'NORM',
                6 => 'OLEH',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikCollection::class,
            'service_name' => 'PenilaianFisik',
        ],
        'MedicalRecord\\V1\\Rest\\PenilaianNyeri\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriResource::class,
            'route_name' => 'medical-record.rest.penilaian-nyeri',
            'route_identifier_name' => 'id',
            'collection_name' => 'penilaian_nyeri',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'HISTORY',
                4 => 'sort',
                5 => 'limit',
                6 => 'start',
                7 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriCollection::class,
            'service_name' => 'PenilaianNyeri',
        ],
        'MedicalRecord\\V1\\Rest\\StatusPediatric\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricResource::class,
            'route_name' => 'medical-record.rest.status-pediatric',
            'route_identifier_name' => 'id',
            'collection_name' => 'status_pediatric',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'sort',
                6 => 'start',
                7 => 'limit',
                8 => 'NORM',
                9 => 'PENDAFTARAN',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricCollection::class,
            'service_name' => 'StatusPediatric',
        ],
        'MedicalRecord\\V1\\Rest\\Diagnosis\\Controller' => [
            'listener' => \MedicalRecord\V1\Rest\Diagnosis\DiagnosisResource::class,
            'route_name' => 'medical-record.rest.diagnosis',
            'route_identifier_name' => 'id',
            'collection_name' => 'diagnosis',
            'entity_http_methods' => [
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [
                0 => 'KUNJUNGAN',
                1 => 'STATUS',
                2 => 'OLEH',
                3 => 'HISTORY',
                4 => 'NOT',
                5 => 'sort',
                6 => 'NORM',
            ],
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => \MedicalRecord\V1\Rest\Diagnosis\DiagnosisEntity::class,
            'collection_class' => \MedicalRecord\V1\Rest\Diagnosis\DiagnosisCollection::class,
            'service_name' => 'Diagnosis',
        ],
    ],
    'api-tools-content-negotiation' => [
        'controllers' => [
            'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\CPPT\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\RiwayatPemberianObat\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\KeluhanUtama\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\StatusFungsional\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\KondisiSosial\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\EdukasiPasienKeluarga\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\EdukasiEmergency\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PermasalahGiziPasien\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PemeriksaanUmum\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\Fungsional\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PenilaianFisik\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\PenilaianNyeri\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\StatusPediatric\\Controller' => 'Json',
            'MedicalRecord\\V1\\Rest\\Diagnosis\\Controller' => 'Json',
        ],
        'accept_whitelist' => [
            'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\CPPT\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatPemberianObat\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\KeluhanUtama\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\StatusFungsional\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\KondisiSosial\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\EdukasiPasienKeluarga\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\EdukasiEmergency\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PermasalahGiziPasien\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PemeriksaanUmum\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Fungsional\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PenilaianFisik\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PenilaianNyeri\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\StatusPediatric\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Diagnosis\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ],
        ],
        'content_type_whitelist' => [
            'MedicalRecord\\V1\\Rest\\Diagnosa\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Operasi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD9CM\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\OperasiDiTindakan\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\ICD10Kematian\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Anamnesis\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PemeriksaanFisik\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatPerjalananPenyakit\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatAlergi\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\TandaVital\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PeminjamanBerkas1\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\CPPT\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\RiwayatPemberianObat\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\KeluhanUtama\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\StatusFungsional\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\KondisiSosial\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\EdukasiPasienKeluarga\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\EdukasiEmergency\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PermasalahGiziPasien\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PemeriksaanUmum\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Fungsional\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PenilaianFisik\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\PenilaianNyeri\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\StatusPediatric\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
            'MedicalRecord\\V1\\Rest\\Diagnosis\\Controller' => [
                0 => 'application/vnd.medical-record.v1+json',
                1 => 'application/json',
            ],
        ],
    ],
    'api-tools-hal' => [
        'metadata_map' => [
            \MedicalRecord\V1\Rest\Diagnosa\DiagnosaEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.diagnosa',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \MedicalRecord\V1\Rest\Diagnosa\DiagnosaCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.diagnosa',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\Operasi\OperasiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \MedicalRecord\V1\Rest\Operasi\OperasiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\ICD10\ICD10Entity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd10',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \MedicalRecord\V1\Rest\ICD10\ICD10Collection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd10',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\ICD9CM\ICD9CMEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd9-cm',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \MedicalRecord\V1\Rest\ICD9CM\ICD9CMCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.icd9-cm',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi-di-tindakan',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \MedicalRecord\V1\Rest\OperasiDiTindakan\OperasiDiTindakanCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.operasi-di-tindakan',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.icd10-kematian',
                'route_identifier_name' => 'id',
                'hydrator' => 'Laminas\\Stdlib\\Hydrator\\ArraySerializableHydrator',
            ],
            \MedicalRecord\V1\Rest\ICD10Kematian\ICD10KematianCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.icd10-kematian',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\Anamnesis\AnamnesisEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.anamnesis',
                'route_identifier_name' => 'anamnesis_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\Anamnesis\AnamnesisCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.anamnesis',
                'route_identifier_name' => 'anamnesis_id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.pemeriksaan-fisik',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PemeriksaanFisik\PemeriksaanFisikCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.pemeriksaan-fisik',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.riwayat-perjalanan-penyakit',
                'route_identifier_name' => 'riwayat_perjalanan_penyakit_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\RiwayatPerjalananPenyakit\RiwayatPerjalananPenyakitCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.riwayat-perjalanan-penyakit',
                'route_identifier_name' => 'riwayat_perjalanan_penyakit_id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.riwayat-alergi',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\RiwayatAlergi\RiwayatAlergiCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.riwayat-alergi',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\TandaVital\TandaVitalEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.tanda-vital',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\TandaVital\TandaVitalCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.tanda-vital',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas\PeminjamanBerkasCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Entity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas1',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PeminjamanBerkas1\PeminjamanBerkas1Collection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.peminjaman-berkas1',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\CPPT\CPPTEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.cppt',
                'route_identifier_name' => 'cppt_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\CPPT\CPPTCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.cppt',
                'route_identifier_name' => 'cppt_id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.riwayat-pemberian-obat',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\RiwayatPemberianObat\RiwayatPemberianObatCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.riwayat-pemberian-obat',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.keluhan-utama',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\KeluhanUtama\KeluhanUtamaCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.keluhan-utama',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.status-fungsional',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\StatusFungsional\StatusFungsionalCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.status-fungsional',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.kondisi-sosial',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\KondisiSosial\KondisiSosialCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.kondisi-sosial',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.edukasi-pasien-keluarga',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\EdukasiPasienKeluarga\EdukasiPasienKeluargaCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.edukasi-pasien-keluarga',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyEntity::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.edukasi-emergency',
                'route_identifier_name' => 'edukasi_emergency_id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\EdukasiEmergency\EdukasiEmergencyCollection::class => [
                'entity_identifier_name' => 'id',
                'route_name' => 'medical-record.rest.edukasi-emergency',
                'route_identifier_name' => 'edukasi_emergency_id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.permasalah-gizi-pasien',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PermasalahGiziPasien\PermasalahGiziPasienCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.permasalah-gizi-pasien',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.pemeriksaan-umum',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PemeriksaanUmum\PemeriksaanUmumCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.pemeriksaan-umum',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\Fungsional\FungsionalEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.fungsional',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\Fungsional\FungsionalCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.fungsional',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.penilaian-fisik',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PenilaianFisik\PenilaianFisikCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.penilaian-fisik',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.penilaian-nyeri',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\PenilaianNyeri\PenilaianNyeriCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.penilaian-nyeri',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.status-pediatric',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\StatusPediatric\StatusPediatricCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.status-pediatric',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
            \MedicalRecord\V1\Rest\Diagnosis\DiagnosisEntity::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.diagnosis',
                'route_identifier_name' => 'id',
                'hydrator' => \Laminas\Hydrator\ArraySerializableHydrator::class,
            ],
            \MedicalRecord\V1\Rest\Diagnosis\DiagnosisCollection::class => [
                'entity_identifier_name' => 'ID',
                'route_name' => 'medical-record.rest.diagnosis',
                'route_identifier_name' => 'id',
                'is_collection' => true,
            ],
        ],
    ],
    'controllers' => [
        'factories' => [],
    ],
    'api-tools-rpc' => [],
];
